(package "auto-highlight-symbol"
         "1.61"
         "Automatic highlighting current symbol minor mode")

(website-url "http://github.com/jcs-elpa/auto-highlight-symbol")
(keywords "highlight" "face" "convenience" "match")

(package-file "auto-highlight-symbol.el")

(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "ht")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
